### PR TITLE
add ext object to collections

### PR DESCRIPTION
**Pull request by hermanvand**
implements #140

### CODE REVIEW

**Review by jelmerderonde — APPROVED** [review]
Ziet er goed uit zo!

**Review by jelmerderonde — CHANGES_REQUESTED** [review]
Please add a changelog

**Review by hamrt — APPROVED** [review]
Ext objects on the collections looks good. 
I've created a CHANGELOG.md file in root where changes can now be added prior to release.

**Comment by hamrt** [comment]
changelog should not be a stopping issue for this merge information can be added as soon as PR #152 has been reviewed and merged

**Review by jelmerderonde — COMMENTED** [review]
Als #152 gemerged is kan deze PR daarop gerebased worden. Dan kan de changelog gelijk toegevoegd worden.

Maar we kunnen het ook achteraf doen, ik zal deze approven want de changes an sich zijn prima zo!

**Review by jelmerderonde — APPROVED** [review]

**Pull request merged**
